# This script merges the existing scrambles from twisty-timer with the new ones from cstimer, ensuring no duplicates.

INPUT_EXISTING = "scrambles/twisty-timer.txt" # input file from twisty-timer export
INPUT_NEW = "temp/dedup-ready.txt" # intermediate file generated by convert_cstimer() function to remove duplicates before merging
OUTPUT_FILE = "f2-step-twisty-result.txt" # final output file after merging and deduplication

def normalize_scramble(scramble):
    return " ".join(scramble.split())

def parse_line(line):
    line = line.strip()
    if not line:
        return None

    parts = line.split(";")
    if len(parts) != 3:
        return None

    scramble = normalize_scramble(parts[1].strip().strip('"'))
    return scramble, line

def main():
    existing_scrambles = set()
    final_lines = []

    # 🔹 Load existing (Twisty)
    with open(INPUT_EXISTING, "r", encoding="utf-8") as f:
        for line in f:
            parsed = parse_line(line)
            if parsed:
                scramble, original_line = parsed
                if scramble not in existing_scrambles:
                    existing_scrambles.add(scramble)
                    final_lines.append(original_line)

    print(f"📦 Loaded existing: {len(final_lines)}")

    added = 0

    # 🔹 Add new (csTimer)
    with open(INPUT_NEW, "r", encoding="utf-8") as f:
        for line in f:
            parsed = parse_line(line)
            if not parsed:
                continue

            scramble, original_line = parsed

            if scramble not in existing_scrambles:
                existing_scrambles.add(scramble)
                final_lines.append(original_line)
                added += 1

    print(f"🆕 Added from csTimer: {added}")
    print(f"📊 Final total: {len(final_lines)}")

    with open(OUTPUT_FILE, "w", encoding="utf-8") as f:
        f.write("\n".join(final_lines))

    print(f"✅ DONE → {OUTPUT_FILE}")

if __name__ == "__main__":
    main()